#!/usr/bin/env python3
"""Refresh the shared footer markup across all static HTML pages."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FOOTER_PATTERN = re.compile(
    r'<footer class="site-footer">.*?</footer>',
    flags=re.DOTALL,
)


def root_prefix(page: Path) -> str:
    relative_parent = page.relative_to(ROOT).parent
    depth = 0 if relative_parent == Path(".") else len(relative_parent.parts)
    return "./" if depth == 0 else "../" * depth


def footer_markup(prefix: str) -> str:
    return f"""<!-- Shared footer: generated by tools/refresh_shared_ui.py -->
<footer class="site-footer">
  <div class="container footer-cta">
    <div class="footer-cta-copy">
      <span class="footer-kicker">معاينة وخدمة ميدانية داخل الرياض</span>
      <h2>جاهز تبدأ مشروع البلاط؟</h2>
      <p>أرسل نوع الخدمة وصور المساحة والحي، وسنرتب معك تفاصيل المعاينة والخطوة المناسبة.</p>
    </div>
    <div class="footer-cta-actions">
      <a class="button button-primary" href="https://wa.me/966567372527?text=مرحبًا، أحتاج معاينة لمشروع بلاط في الرياض" target="_blank" rel="noopener">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.5 9.5 0 0 1-4-1l-5 1 1.2-4.5A8.5 8.5 0 1 1 21 11.5z"/><path d="M9 8c.5 3 2 4.5 5 5"/></svg>
        أرسل تفاصيل المشروع
      </a>
      <a class="button footer-call-button" href="tel:0567372527">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.35 1.9.65 2.8a2 2 0 0 1-.45 2.11L8.04 9.9a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.3 1.84.52 2.8.65A2 2 0 0 1 22 16.92z"/></svg>
        اتصال مباشر
      </a>
    </div>
  </div>

  <div class="container footer-main">
    <div class="footer-brand">
      <a class="brand footer-logo" href="{prefix}">
        <img src="{prefix}assets/images/logo-mark.svg" width="56" height="56" alt="شعار المبلط عادل">
        <span><strong>المبلط عادل</strong><small>تركيب وتشطيب البلاط في الرياض</small></span>
      </a>
      <p>خدمات تركيب البلاط والسيراميك والبورسلان والرخام، مع العزل والترميم وتشطيب التفاصيل بعناية.</p>
      <div class="footer-badges" aria-label="مميزات الخدمة">
        <span>خدمة ميدانية</span>
        <span>جميع أحياء الرياض</span>
      </div>
    </div>

    <nav class="footer-section" aria-label="روابط الموقع">
      <h2>روابط مهمة</h2>
      <ul>
        <li><a href="{prefix}">الرئيسية</a></li>
        <li><a href="{prefix}services/">جميع الخدمات</a></li>
        <li><a href="{prefix}blog/">دليل البلاط</a></li>
        <li><a href="{prefix}#contact">طلب معاينة</a></li>
      </ul>
    </nav>

    <nav class="footer-section" aria-label="أهم خدمات البلاط">
      <h2>خدمات مطلوبة</h2>
      <ul>
        <li><a href="{prefix}services/tile-installation/">تركيب البلاط</a></li>
        <li><a href="{prefix}services/ceramic-installation/">تركيب السيراميك</a></li>
        <li><a href="{prefix}services/porcelain-installation/">تركيب البورسلان</a></li>
        <li><a href="{prefix}services/tile-repair/">ترميم وإصلاح البلاط</a></li>
      </ul>
    </nav>

    <div class="footer-section footer-contact">
      <h2>تواصل معنا</h2>
      <a class="footer-contact-link" href="tel:0567372527">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.35 1.9.65 2.8a2 2 0 0 1-.45 2.11L8.04 9.9a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.3 1.84.52 2.8.65A2 2 0 0 1 22 16.92z"/></svg>
        <span><small>اتصال مباشر</small><strong dir="ltr">056 737 2527</strong></span>
      </a>
      <a class="footer-contact-link" href="https://wa.me/966567372527?text=مرحبًا، أحتاج خدمة بلاط في الرياض" target="_blank" rel="noopener">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.5 9.5 0 0 1-4-1l-5 1 1.2-4.5A8.5 8.5 0 1 1 21 11.5z"/><path d="M9 8c.5 3 2 4.5 5 5"/></svg>
        <span><small>واتساب</small><strong>المبلط عادل</strong></span>
      </a>
      <div class="footer-location">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0z"/><circle cx="12" cy="10" r="2.5"/></svg>
        <span><small>نطاق الخدمة</small><strong>مدينة الرياض</strong></span>
      </div>
    </div>
  </div>

  <div class="container footer-bottom developer-credit">
    <p class="footer-copyright">جميع الحقوق محفوظة لـ المبلط عادل © <span data-current-year>2026</span></p>
    <div class="dev-signature" aria-label="توقيع مطور الموقع">
      <span class="dev-mark" aria-hidden="true">E</span>
      <span class="dev-copy">
        <small>تم التصميم والتطوير بواسطة · Developed by</small>
        <a class="dev-name" href="https://eslam-elshikh.com/" target="_blank" rel="noopener">المهندس إسلام الشيخ · Eng. Eslam Elshikh</a>
        <span class="dev-roles">Cybersecurity Engineer · Web Developer · Google Product Expert</span>
      </span>
      <a class="dev-whatsapp" href="https://wa.me/966547194788?text=مرحبًا المهندس إسلام الشيخ، أريد الاستفسار عن تصميم موقع" target="_blank" rel="noopener">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.5 9.5 0 0 1-4-1l-5 1 1.2-4.5A8.5 8.5 0 1 1 21 11.5z"/><path d="M9 8c.5 3 2 4.5 5 5"/></svg>
        تواصل واتساب
      </a>
    </div>
  </div>
</footer>"""


def main() -> None:
    pages = sorted(ROOT.rglob("*.html"))
    updated_count = 0

    for page in pages:
        source = page.read_text(encoding="utf-8")
        replacement = footer_markup(root_prefix(page))
        updated, substitutions = FOOTER_PATTERN.subn(replacement, source, count=1)
        if substitutions != 1:
            raise RuntimeError(f"Expected one footer in {page.relative_to(ROOT)}")
        if updated != source:
            page.write_text(updated, encoding="utf-8")
            updated_count += 1

    print(f"Updated shared footer in {updated_count} HTML pages.")


if __name__ == "__main__":
    main()
